apiVersion: v1
kind: Service
metadata:
  namespace: static
  name: aedius
  labels:
    app: aedius
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
spec:
  type: NodePort
  selector:
    app: aedius
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 51.254.129.65