apiVersion: v1
kind: Service
metadata:
  namespace: static
  name: proxy
  labels:
    app: proxy
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
spec:
  type: NodePort
  selector:
    app: proxy
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 51.254.129.65
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: static
  labels:
    app: proxy
    chart: {{ .Chart.Name | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
      chart: {{ .Chart.Name | quote }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: proxy
        chart: {{ .Chart.Name | quote }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: proxy
          image: "{{ (index .Values.images "proxy").repository }}:{{ (index .Values.images "aedius").tag }}"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-docker-login